### PR TITLE
Created Horizontal form-groups

### PR DESCRIPTION
**Pull request by gojirian**
All new snippets have an h added to the end 

I did not see a need to have horizontal  form-group versions of the Radio, Button and hidden snippets

### CODE REVIEW

**Comment by gojirian** [comment]
Had to add in missing double quotes on checkbox

**Comment by redgluten** [comment]
Thanks a lot. I was planning to make those. :)

**Comment by weip** [comment]
You should add larform command in readme because I was looking for a snippet and yours was already doing it but I didn't see anything in documentation.

**Comment by redgluten** [comment]
You’re right, that’s done and it comes with a form-model binding scaffolding snippet too. :)

**Pull request merged**
